//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="This Field is Required")]
        public string Name { get; set; }


        [Required(ErrorMessage = "This Field is Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [DataType(DataType.Date)]
        public System.DateTime Dob { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public string Description { get; set; }
    }
}
